### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by podlebar** [nuxt-community/algolia-module#85]
### Version

@nuxtjs/algolia: 1.1.1
nuxt: 3.0.0-rc.6

### Reproduction Link

none

but with version 1.1.0 is seems to work

### Steps to reproduce
- install nuxt
- install this plugin as described here: https://algolia.nuxtjs.org/getting-started/quick-start

### What is Expected?
nuxt starts correctly

### What is actually happening?
nuxt does not start anymore and throws following error:
```
 ERROR  Cannot start nuxt:  nuxtCtx.tryUse is not a function                                              15:01:10

  at useNuxt (node_modules/@nuxtjs/algolia/node_modules/@nuxt/kit/dist/index.mjs:47:28)
  at addPlugin (node_modules/@nuxtjs/algolia/node_modules/@nuxt/kit/dist/index.mjs:434:16)
  at setup (node_modules/@nuxtjs/algolia/dist/module.mjs:183:5)
  at Object.normalizedModule (node_modules/@nuxtjs/algolia/node_modules/@nuxt/kit/dist/index.mjs:624:29)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:432:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1423:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6750:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6795:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:46:20)
```

**Comment by Baroshem** [comment]
Hey, @podlebar ,

Could you please create a reproduction repository or a project in stackblitz? This issue is really strange and I have not encountered it yet

**Comment by podlebar** [comment]
everything works fine with nuxt: 3.0.0-rc.8
